/// @description GML references to YUI assets to prevent them from being stripped
function __yui_asset_references() {
	var assets = [
		yui_ease_in_curve,
		yui_linear_curve,
		yui_wave_curve,
		fnt_yui_body,
		fnt_yui_body_bold,
		fnt_yui_subtitle,
		fnt_yui_title,
		yui_fnt_mono,
		yui_icon_hamburger_menu,
		yui_icon_checkmark,
		yui_icon_redo,
		yui_icon_undo,
		yui_icon_contract,
		yui_icon_expand,
		yui_icon_resize_h,
		yui_icon_resize_v,
		yui_icon_move,
		yui_icon_info,
		yui_icon_full_folder,
		yui_icon_open_folder,
		yui_icon_share,
		yui_icon_layers,
		yui_icon_trash,
		yui_icon_64,
		yui_icon_64_centered,
		yui_icon_128,
		yui_panel_bg,
		yui_button_bg,
		yui_error_icon,
		yui_down_arrow_64,
		yui_white_pixel,
	];
}